import {
  ArrowRight,
  BadgeCheck,
  Box,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleX,
  Clapperboard,
  Clock,
  ExternalLink,
  FileText,
  Handshake,
  History,
  LayoutGrid,
  Lock,
  Maximize2,
  MessagesSquare,
  Network,
  Pause,
  PenLine,
  Play,
  ReceiptText,
  ScanBarcode,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  TriangleAlert,
  Truck,
  Wallet,
  X,
  type LucideIcon,
} from "lucide-react";

/** Thin wrapper over Lucide so the app keeps one icon vocabulary. */
const icons = {
  overview: LayoutGrid,
  conditions: SlidersHorizontal,
  negotiation: MessagesSquare,
  agreement: Handshake,
  audit: History,
  arrow: ArrowRight,
  check: Check,
  alert: CircleAlert,
  clock: Clock,
  wallet: Wallet,
  spark: Sparkles,
  box: Box,
  shield: ShieldCheck,
  close: X,
  chevron: ChevronDown,
  prev: ChevronLeft,
  next: ChevronRight,
  file: FileText,
  network: Network,
  lock: Lock,
  pen: PenLine,
  truck: Truck,
  camera: Camera,
  video: Clapperboard,
  receipt: ReceiptText,
  serial: ScanBarcode,
  warranty: BadgeCheck,
  play: Play,
  pause: Pause,
  expand: Maximize2,
  external: ExternalLink,
  pass: CircleCheck,
  warn: TriangleAlert,
  block: CircleX,
  idle: CircleHelp,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export function Icon({ name, size = 18, className }: { name: IconName; size?: number; className?: string }) {
  const Component = icons[name];
  return <Component size={size} strokeWidth={2} className={className} aria-hidden="true" />;
}
